### ISSUE TITLE
[Bug]: Docker-Composer PHP Service couldn't be detected when profile is set

### ISSUE THREAD

**Issue by plakhin** [beyondcode/tinkerwell-community#534]
### Operating system

Windows 10

### Laravel Version

v8.88.1

### PHP Version

PHP 8.0.13

### Project Location

Remote (Docker)

### Bug description

When `profile` is set for PHP Service container it is not being detected by Tinkerwell app.
![image](https://user-images.githubusercontent.com/25561058/147660304-06920ee4-d7a1-4a81-bdda-e32743882031.png)

### Steps to reproduce

add `profile` to PHP Service container in `docker-compose.yml`. 

```
...
    laravel.test:
        profiles: ["web"]
        build:
            context: ./vendor/laravel/sail/runtimes/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
...
```
